# Generated by Django 5.2.3 on 2025-07-06 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quit_date',
            field=models.DateField(default=datetime.date(2025, 7, 6)),
        ),
    ]
