# Generated by Django 5.2.3 on 2025-07-06 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_quit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quit_date',
            field=models.DateField(verbose_name=datetime.date(2025, 7, 6)),
        ),
    ]
